# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class TestProductpage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_productpage(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1296, 736)
    self.driver.find_element(By.CSS_SELECTOR, ".kuMitT .navicon").click()
    new_link = WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "NEW")))
    new_link.click()
    self.driver.find_element(By.CSS_SELECTOR, ".navicon").click()

  
