services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3006
selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    depends_on:
      - web